spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://175.125.177.207:6036/MYBOX?autoReconnect=true
      username: root
      password:
      mapper-locations: classpath:/mapper/**/*.xml


server:
  port: 8081
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled : true
    path: /error
    include-message: always
active:
  server: local
  max-http-header-size: 0


springfox:
  documentation:
    swaggerUi:
      baseUrl: /app
    openApi:
      v3:
        path: /app/v3/api-docs
    swagger:
      v2:
        path: /app/v2/api-docs